"use client";

import { useEffect, useMemo, useState } from "react";
import { createClient } from "@/lib/supabase/client";
import Shell from "@/components/Shell";
import { Plus, Save, Trash2, Copy, Image as ImageIcon, X, Search, GripVertical, Eye, EyeOff, Upload, FolderPlus } from "lucide-react";
import "./admin.css";

type Category = { id:string; name:string; slug:string; description:string|null; image_url:string|null; sort_order:number; active:boolean };
type Option = { id?:string; option_group:string; label:string; price_delta:number; sort_order:number; active?:boolean };
type Product = { id:string; category_id:string|null; name:string; slug:string; description:string|null; image_url:string|null; gallery_urls:any; specs:any; price_from:number; featured:boolean; promotion:any; active:boolean; sort_order:number };

const emptyProduct: Omit<Product,"id"> = {category_id:null,name:"",slug:"",description:"",image_url:"",gallery_urls:[],specs:[],price_from:0,featured:false,promotion:null,active:true,sort_order:0};
const money=(n:number)=>`Gs. ${new Intl.NumberFormat("es-PY").format(Math.round(Number(n)||0))}`;
const slugify=(s:string)=>s.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"");

export default function CatalogAdmin(){
 const sb=createClient();
 const [products,setProducts]=useState<Product[]>([]); const [categories,setCategories]=useState<Category[]>([]); const [selected,setSelected]=useState<Product|null>(null);
 const [options,setOptions]=useState<Option[]>([]); const [search,setSearch]=useState(""); const [tab,setTab]=useState<"products"|"categories">("products"); const [loading,setLoading]=useState(true); const [saving,setSaving]=useState(false); const [msg,setMsg]=useState(""); const [role,setRole]=useState("");
 const [newCat,setNewCat]=useState({name:"",description:"",image_url:""});

 async function load(){setLoading(true); const [{data:p},{data:c},{data:{user}}]=await Promise.all([sb.from("catalog_products").select("*").order("sort_order").order("name"),sb.from("catalog_categories").select("*").order("sort_order").order("name"),sb.auth.getUser()]);
  if(user){const {data:pr}=await sb.from("profiles").select("role:roles(name)").eq("id",user.id).single(); const r:any=pr?.role; setRole(Array.isArray(r)?r[0]?.name||"":r?.name||"");}
  setProducts((p||[]) as Product[]); setCategories((c||[]) as Category[]); setLoading(false);
 }
 useEffect(()=>{load()},[]);
 useEffect(()=>{(async()=>{if(selected?.id){const {data}=await sb.from("catalog_options").select("*").eq("product_id",selected.id).order("option_group").order("sort_order");setOptions((data||[]) as Option[])}else setOptions([])})()},[selected?.id]);

 const filtered=useMemo(()=>products.filter(p=>p.name.toLowerCase().includes(search.toLowerCase())||p.slug.includes(search.toLowerCase())),[products,search]);
 if(role && role!=="administrador") return <Shell title="Catálogo"><div className="blocked"><h1>Acceso restringido</h1><p>Solo el administrador puede gestionar el catálogo.</p></div></Shell>;

 function edit(p:Product){setSelected({...p,gallery_urls:Array.isArray(p.gallery_urls)?p.gallery_urls:[],specs:Array.isArray(p.specs)?p.specs:[]});setMsg("")}
 function newProduct(){setSelected({id:"",...emptyProduct,name:"Nuevo producto",slug:"nuevo-producto",sort_order:products.length+1});setOptions([]);setMsg("")}
 async function saveProduct(){if(!selected?.name.trim()) return setMsg("El nombre del producto es obligatorio."); setSaving(true); setMsg("");
  const payload={category_id:selected.category_id||null,name:selected.name,slug:selected.slug||slugify(selected.name),description:selected.description||"",image_url:selected.image_url||"",gallery_urls:Array.isArray(selected.gallery_urls)?selected.gallery_urls:[],specs:Array.isArray(selected.specs)?selected.specs:[],price_from:Number(selected.price_from)||0,featured:selected.featured,active:selected.active,sort_order:Number(selected.sort_order)||0,promotion:selected.promotion||null};
  const result=selected.id?await sb.from("catalog_products").update(payload).eq("id",selected.id).select().single():await sb.from("catalog_products").insert(payload).select().single();
  if(result.error){setMsg(result.error.message);setSaving(false);return} const saved=result.data as Product;
  if(selected.id) await sb.from("catalog_options").delete().eq("product_id",selected.id); const valid=options.filter(o=>o.option_group.trim()&&o.label.trim()).map((o,i)=>({product_id:saved.id,option_group:o.option_group.trim(),label:o.label.trim(),price_delta:Number(o.price_delta)||0,sort_order:i,active:o.active!==false})); if(valid.length) await sb.from("catalog_options").insert(valid);
  setSelected(saved); await load(); setSelected(saved); setSaving(false); setMsg("Producto guardado correctamente.");
 }
 async function duplicate(){if(!selected) return; const copy={...selected,id:"",name:`${selected.name} - copia`,slug:`${selected.slug}-copia`,sort_order:products.length+1}; setSelected(copy); setMsg("Copia preparada. Presioná Guardar producto para crearla.")}
 async function removeProduct(){if(!selected?.id||!confirm(`¿Eliminar "${selected.name}"?`))return; const {error}=await sb.from("catalog_products").delete().eq("id",selected.id); if(error)setMsg(error.message);else{setSelected(null);await load();setMsg("Producto eliminado.")}}
 async function toggleProduct(p:Product){await sb.from("catalog_products").update({active:!p.active}).eq("id",p.id);await load();if(selected?.id===p.id)setSelected({...p,active:!p.active})}
 async function uploadImage(file:File, target:"main"|"gallery"){if(!file||!selected)return; const ext=file.name.split(".").pop()||"jpg";const path=`products/${crypto.randomUUID()}.${ext}`;const {error}=await sb.storage.from("catalog-media").upload(path,file,{upsert:false});if(error)return setMsg(error.message);const {data}=sb.storage.from("catalog-media").getPublicUrl(path);if(target==="main")setSelected({...selected,image_url:data.publicUrl});else setSelected({...selected,gallery_urls:[...(selected.gallery_urls||[]),data.publicUrl]});}
 async function addCategory(){if(!newCat.name.trim())return; const {error}=await sb.from("catalog_categories").insert({name:newCat.name.trim(),slug:slugify(newCat.name),description:newCat.description,image_url:newCat.image_url,sort_order:categories.length+1});if(error)setMsg(error.message);else{setNewCat({name:"",description:"",image_url:""});await load();setMsg("Categoría creada.")}}
 async function updateCategory(c:Category, patch:Partial<Category>){await sb.from("catalog_categories").update(patch).eq("id",c.id);setCategories(cs=>cs.map(x=>x.id===c.id?{...x,...patch}:x))}
 async function deleteCategory(c:Category){if(!confirm(`¿Eliminar la categoría "${c.name}"?`))return; const {error}=await sb.from("catalog_categories").delete().eq("id",c.id);if(error)setMsg("No se puede eliminar si hay productos vinculados. Desactivala en su lugar.");else await load()}

 return <Shell title="Administrador de catálogo"><div className="catalog-admin">
  <div className="admin-head"><div><div className="eyebrow">PROPUBLIC · CATÁLOGO</div><h1>Administrador de catálogo</h1><p>Gestioná productos, precios, variantes, fotos y categorías sin tocar código.</p></div><div className="head-actions"><button className="btn ghost" onClick={()=>setTab("categories")}><FolderPlus size={17}/> Categorías</button><button className="btn primary" onClick={newProduct}><Plus size={17}/> Nuevo producto</button></div></div>
  {msg&&<div className="notice">{msg}<button onClick={()=>setMsg("")}><X size={15}/></button></div>}
  <div className="tabs"><button className={tab==="products"?"active":""} onClick={()=>setTab("products")}>Productos <span>{products.length}</span></button><button className={tab==="categories"?"active":""} onClick={()=>setTab("categories")}>Categorías <span>{categories.length}</span></button></div>
  {tab==="products"?<div className="workspace">
   <aside className="product-list"><div className="search"><Search size={17}/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar producto..."/></div><button className="new-inline" onClick={newProduct}><Plus size={16}/> Agregar producto</button>{loading?<p className="muted">Cargando...</p>:filtered.map(p=><button key={p.id} className={`product-row ${selected?.id===p.id?"selected":""}`} onClick={()=>edit(p)}><div className="thumb">{p.image_url?<img src={p.image_url} alt=""/>:<ImageIcon size={20}/>}</div><div className="row-copy"><strong>{p.name}</strong><small>{categories.find(c=>c.id===p.category_id)?.name||"Sin categoría"}</small><b>{money(Number(p.price_from))}</b></div><span className={p.active?"dot on":"dot"}/></button>)}</aside>
   <section className="editor">{selected?<>
    <div className="editor-head"><div><span className="status-pill">{selected.active?"PUBLICADO":"OCULTO"}</span><h2>{selected.name}</h2><p>Ficha comercial y configuración del producto</p></div><div className="editor-actions"><button className="icon-btn" title="Duplicar" onClick={duplicate}><Copy size={17}/></button><button className="icon-btn" title={selected.active?"Ocultar":"Publicar"} onClick={()=>selected.id&&toggleProduct(selected)}>{selected.active?<EyeOff size={17}/>:<Eye size={17}/>}</button>{selected.id&&<button className="icon-btn danger" title="Eliminar" onClick={removeProduct}><Trash2 size={17}/></button>}<button className="btn primary" onClick={saveProduct} disabled={saving}><Save size={17}/>{saving?"Guardando...":"Guardar producto"}</button></div></div>
    <div className="form-grid">
      <div className="panel full"><div className="panel-title">Información principal</div><div className="fields two"><label>Nombre<input value={selected.name} onChange={e=>setSelected({...selected,name:e.target.value,slug:selected.id?selected.slug:slugify(e.target.value)})}/></label><label>SKU / identificador visual<input value={selected.slug} onChange={e=>setSelected({...selected,slug:e.target.value})}/></label><label>Categoría<select value={selected.category_id||""} onChange={e=>setSelected({...selected,category_id:e.target.value||null})}><option value="">Sin categoría</option>{categories.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>Precio desde (Gs.)<input type="number" min="0" value={selected.price_from} onChange={e=>setSelected({...selected,price_from:Number(e.target.value)})}/></label><label className="wide">Descripción<textarea rows={4} value={selected.description||""} onChange={e=>setSelected({...selected,description:e.target.value})}/></label></div><div className="checks"><label><input type="checkbox" checked={selected.active} onChange={e=>setSelected({...selected,active:e.target.checked})}/> Visible en el catálogo</label><label><input type="checkbox" checked={selected.featured} onChange={e=>setSelected({...selected,featured:e.target.checked})}/> Producto destacado</label></div></div>
      <div className="panel"><div className="panel-title">Foto principal</div><div className="image-box">{selected.image_url?<img src={selected.image_url} alt="Vista previa"/>:<div className="empty-image"><ImageIcon size={28}/><span>Sin imagen</span></div>}<label className="upload"><Upload size={16}/> Subir imagen<input type="file" accept="image/*" onChange={e=>e.target.files?.[0]&&uploadImage(e.target.files[0],"main")}/></label></div><label>O pegar URL<input value={selected.image_url||""} onChange={e=>setSelected({...selected,image_url:e.target.value})} placeholder="https://..."/></label></div>
      <div className="panel"><div className="panel-title">Galería</div><div className="gallery-list">{(selected.gallery_urls||[]).map((url:string,i:number)=><div className="gallery-item" key={url+i}><img src={url} alt=""/><button onClick={()=>setSelected({...selected,gallery_urls:selected.gallery_urls.filter((_:string,j:number)=>j!==i)})}><X size={14}/></button></div>)}</div><label className="upload full-upload"><Upload size={16}/> Agregar foto<input type="file" accept="image/*" onChange={e=>e.target.files?.[0]&&uploadImage(e.target.files[0],"gallery")}/></label></div>
      <div className="panel full"><div className="panel-title">Especificaciones técnicas</div><div className="specs">{(selected.specs||[]).map((s:any,i:number)=><div className="spec-row" key={i}><input placeholder="Ej. Material" value={s.label||""} onChange={e=>{const a=[...(selected.specs||[])];a[i]={...a[i],label:e.target.value};setSelected({...selected,specs:a})}}/><input placeholder="Ej. Tela poliéster" value={s.value||""} onChange={e=>{const a=[...(selected.specs||[])];a[i]={...a[i],value:e.target.value};setSelected({...selected,specs:a})}}/><button className="icon-btn danger" onClick={()=>setSelected({...selected,specs:selected.specs.filter((_:any,j:number)=>j!==i)})}><Trash2 size={15}/></button></div>)}<button className="add-line" onClick={()=>setSelected({...selected,specs:[...(selected.specs||[]),{label:"",value:""}]})}><Plus size={15}/> Agregar especificación</button></div></div>
      <div className="panel full"><div className="panel-title">Opciones y precio dinámico</div><p className="panel-help">Creá grupos como Tamaño, Configuración, Impresión, Base o Mástil. El precio de cada opción se suma al precio base.</p><div className="options">{options.map((o,i)=><div className="option-row" key={o.id||i}><input className="group" placeholder="Grupo" value={o.option_group} onChange={e=>{const a=[...options];a[i]={...a[i],option_group:e.target.value};setOptions(a)}}/><input placeholder="Opción" value={o.label} onChange={e=>{const a=[...options];a[i]={...a[i],label:e.target.value};setOptions(a)}}/><div className="price-input"><span>Gs.</span><input type="number" value={o.price_delta} onChange={e=>{const a=[...options];a[i]={...a[i],price_delta:Number(e.target.value)};setOptions(a)}}/></div><button className="icon-btn danger" onClick={()=>setOptions(options.filter((_,j)=>j!==i))}><Trash2 size={15}/></button></div>)}<button className="add-line" onClick={()=>setOptions([...options,{option_group:"Tamaño",label:"Nueva opción",price_delta:0,sort_order:options.length,active:true}])}><Plus size={15}/> Agregar opción</button></div></div>
      <div className="panel"><div className="panel-title">Promoción</div><div className="fields"><label><input type="checkbox" checked={!!selected.promotion?.active} onChange={e=>setSelected({...selected,promotion:{...(selected.promotion||{}),active:e.target.checked}})}/> Activar promoción</label><label>Precio promocional<input type="number" value={selected.promotion?.price??""} onChange={e=>setSelected({...selected,promotion:{...(selected.promotion||{}),price:Number(e.target.value)}})}/></label><label>Descuento %<input type="number" min="0" max="100" value={selected.promotion?.percent??""} onChange={e=>setSelected({...selected,promotion:{...(selected.promotion||{}),percent:Number(e.target.value)}})}/></label></div></div>
      <div className="panel"><div className="panel-title">Orden y visibilidad</div><label>Orden<input type="number" value={selected.sort_order} onChange={e=>setSelected({...selected,sort_order:Number(e.target.value)})}/></label><div className="mini-preview"><span className="dot on"/> {selected.featured?"Aparecerá en Productos destacados":"Producto normal"}</div></div>
    </div>
   </>:<div className="empty-editor"><FolderPlus size={42}/><h2>Seleccioná un producto</h2><p>O creá uno nuevo para comenzar.</p><button className="btn primary" onClick={newProduct}><Plus size={17}/> Nuevo producto</button></div>}</section>
  </div>:<div className="categories-panel">
    <div className="category-create panel"><div className="panel-title">Nueva categoría</div><div className="category-create-grid"><input placeholder="Nombre de categoría" value={newCat.name} onChange={e=>setNewCat({...newCat,name:e.target.value})}/><input placeholder="Descripción corta" value={newCat.description} onChange={e=>setNewCat({...newCat,description:e.target.value})}/><input placeholder="URL de imagen (opcional)" value={newCat.image_url} onChange={e=>setNewCat({...newCat,image_url:e.target.value})}/><button className="btn primary" onClick={addCategory}><Plus size={16}/> Crear categoría</button></div></div>
    <div className="category-grid">{categories.map(c=><div className="category-card" key={c.id}><div className="category-img">{c.image_url?<img src={c.image_url} alt=""/>:<FolderPlus size={25}/>}</div><div className="category-fields"><label>Nombre<input value={c.name} onChange={e=>updateCategory(c,{name:e.target.value,slug:slugify(e.target.value)})}/></label><label>Descripción<input value={c.description||""} onChange={e=>updateCategory(c,{description:e.target.value})}/></label><label>Imagen<input value={c.image_url||""} onChange={e=>updateCategory(c,{image_url:e.target.value})}/></label><div className="category-actions"><label><input type="checkbox" checked={c.active} onChange={e=>updateCategory(c,{active:e.target.checked})}/> Visible</label><button className="icon-btn danger" onClick={()=>deleteCategory(c)}><Trash2 size={15}/></button></div></div></div>)}</div>
  </div>}
 </div></Shell>
}
