"use client";
import {useEffect,useRef,useState} from "react";
import QRCode from "qrcode";
import {Btn,ErrorBox,Field,Head,Modal,Protected,Status,human,sb} from "@/components/ModuleCommon";

export function QrReader(){return <Protected roles={["administrador","vendedor","disenador","produccion"]}><Reader/></Protected>}
function Reader(){const video=useRef<HTMLVideoElement|null>(null);const stream=useRef<MediaStream|null>(null);const raf=useRef<number>();const[code,setCode]=useState("");const[result,setResult]=useState<any>(null);const[err,setErr]=useState("");const[running,setRunning]=useState(false);const lookup=async(raw:string)=>{setErr("");setResult(null);let v=raw.trim();try{const u=new URL(v);v=u.searchParams.get("code")||u.pathname.split("/").filter(Boolean).pop()||v}catch{}if(!v){setErr("Introduce un código o QR válido.");return}const prefix=v.startsWith("PRE-")?"PRE":v.startsWith("VENT-")?"VENT":v.startsWith("PED-")?"PED":"";const table=prefix==="PRE"?"quotes":prefix==="VENT"?"sales":prefix==="PED"?"orders":"";if(table){const r=await sb.from(table).select("*").eq("number",v).maybeSingle();if(!r.error&&r.data){setResult({table,data:r.data});return}}
 for(const t of ["quotes","sales","orders"]){const r=await sb.from(t).select("*").eq("qr_token",v).maybeSingle();if(!r.error&&r.data){setResult({table:t,data:r.data});return}}
 setErr("No se encontró el registro o no tienes permisos para verlo.")};
 const stop=()=>{if(raf.current)cancelAnimationFrame(raf.current);stream.current?.getTracks().forEach(t=>t.stop());stream.current=null;setRunning(false)};
 useEffect(()=>()=>stop(),[]);
 const start=async()=>{setErr("");if(!(window as any).BarcodeDetector){setErr("Tu navegador no permite lectura QR por cámara. Usa el código manual.");return}try{const s=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:"environment"}}});stream.current=s;setRunning(true);if(video.current){video.current.srcObject=s;await video.current.play()}const Detector=(window as any).BarcodeDetector;const detector=new Detector({formats:["qr_code"]});const loop=async()=>{if(!video.current||video.current.readyState<2){raf.current=requestAnimationFrame(loop);return}try{const found=await detector.detect(video.current);if(found?.[0]?.rawValue){const value=found[0].rawValue;stop();setCode(value);lookup(value);return}}catch{}raf.current=requestAnimationFrame(loop)};raf.current=requestAnimationFrame(loop)}catch{stop();setErr("No fue posible activar la cámara. Revisa el permiso de cámara o usa el ingreso manual.")}};
 return <><Head title="Lector QR ProPublic" description="Consulta segura de presupuestos, ventas y pedidos."/><div className="qrbox"><div className="panel"><div className="scanner">{running?<video ref={video} style={{width:"100%",height:"100%",objectFit:"cover"}} playsInline muted/>:<div className="scannerhint"><strong>Lector QR</strong><span>Activa la cámara para escanear.</span></div>}</div><div className="actions" style={{marginTop:12}}><Btn onClick={start} disabled={running}>Activar cámara</Btn>{running&&<Btn secondary onClick={stop}>Detener</Btn>}</div></div><div className="panel"><Field label="Código o enlace QR"><input value={code} onChange={e=>setCode(e.target.value)} placeholder="PRE-2026-000001"/></Field><Btn onClick={()=>lookup(code)}>Consultar</Btn></div><ErrorBox message={err}/>{result&&<Result result={result}/>}</div></>}
function Result({result}:{result:any}){const[dummy,setDummy]=useState("");const download=async()=>{const n=result.data.number||result.data.code;const token=result.data.qr_token||n;const data=await QRCode.toDataURL(`${location.origin}/lector-qr?code=${encodeURIComponent(token)}`,{width:420,margin:2});const a=document.createElement("a");a.href=data;a.download=`${n}-QR.png`;a.click()};return <div className="panel"><div className="companydata"><div><span>Tipo</span><strong>{result.table}</strong></div><div><span>Código</span><strong>{result.data.number||result.data.code}</strong></div><div><span>Estado</span><Status>{result.data.status}</Status></div></div><Btn onClick={download}>Descargar QR</Btn><pre style={{whiteSpace:"pre-wrap",wordBreak:"break-word",marginTop:16}}>{JSON.stringify(result.data,null,2)}</pre></div>}
